### ISSUE TITLE
Error loading pluging

### ISSUE THREAD

**Issue by divemasterjm** [tystuyfzand/gotify-mqtt#7]
Hi i try to install your plugin but when i start gotify i've got the following message.:
Starting Gotify version 2.2.4@2023-01-10-18:33:52
Loading plugin data/plugins/mqtt-linux-amd64.so
Loading plugin data/plugins/mqtt-linux-amd64.so:Zone.Identifier
panic: error while loading plugin mqtt-linux-amd64.so:Zone.Identifier: plugin.Open("data/plugins/mqtt-linux-amd64.so:Zone.Identifier"): /app/data/plugins/mqtt-linux-amd64.so:Zone.Identifier: file too short
goroutine 1 [running]:
github.com/gotify/server/v2/router.Create(0xc0001192f0, 0xc0001106f0, 0xc00016c300)
	/proj/router/router.go:50 +0x2865
main.main()
	/proj/app.go:51 +0x307

**Comment by divemasterjm** [comment]
just for info, ive downloaded plugin from windows, afetr from linux wget and works perfectly. sorry
